/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package librarity;

import java.awt.Color;

/**
 *
 * @author Bhavneek
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        main_btn_dash = new javax.swing.JPanel();
        main_label_dash = new javax.swing.JLabel();
        main_btn_users = new javax.swing.JPanel();
        main_label_users = new javax.swing.JLabel();
        main_btn_books = new javax.swing.JPanel();
        main_label_books = new javax.swing.JLabel();
        main_btn_issues = new javax.swing.JPanel();
        main_label_issues = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        panel_dash = new javax.swing.JPanel();
        panel_users = new javax.swing.JPanel();
        panel_books = new javax.swing.JPanel();
        panel_issues = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("HelveticaNowDisplay ExtraBold", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Librarity");

        main_btn_dash.setBackground(new java.awt.Color(61, 108, 185));
        main_btn_dash.setForeground(new java.awt.Color(255, 255, 255));
        main_btn_dash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                main_btn_dashMouseClicked(evt);
            }
        });

        main_label_dash.setFont(new java.awt.Font("HelveticaNowDisplay Regular", 0, 14)); // NOI18N
        main_label_dash.setForeground(new java.awt.Color(255, 255, 255));
        main_label_dash.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        main_label_dash.setText("Dashboard");
        main_label_dash.setPreferredSize(new java.awt.Dimension(68, 45));
        main_label_dash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                main_label_dashMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout main_btn_dashLayout = new javax.swing.GroupLayout(main_btn_dash);
        main_btn_dash.setLayout(main_btn_dashLayout);
        main_btn_dashLayout.setHorizontalGroup(
            main_btn_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_btn_dashLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(main_label_dash, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );
        main_btn_dashLayout.setVerticalGroup(
            main_btn_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_btn_dashLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(main_label_dash, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        main_btn_users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                main_btn_usersMouseClicked(evt);
            }
        });

        main_label_users.setFont(new java.awt.Font("HelveticaNowDisplay Regular", 0, 14)); // NOI18N
        main_label_users.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        main_label_users.setText("Users");
        main_label_users.setPreferredSize(new java.awt.Dimension(68, 45));
        main_label_users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                main_label_usersMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout main_btn_usersLayout = new javax.swing.GroupLayout(main_btn_users);
        main_btn_users.setLayout(main_btn_usersLayout);
        main_btn_usersLayout.setHorizontalGroup(
            main_btn_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_btn_usersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(main_label_users, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );
        main_btn_usersLayout.setVerticalGroup(
            main_btn_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_btn_usersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(main_label_users, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        main_btn_books.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                main_btn_booksMouseClicked(evt);
            }
        });

        main_label_books.setFont(new java.awt.Font("HelveticaNowDisplay Regular", 0, 14)); // NOI18N
        main_label_books.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        main_label_books.setText("Books");
        main_label_books.setPreferredSize(new java.awt.Dimension(68, 45));
        main_label_books.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                main_label_booksMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout main_btn_booksLayout = new javax.swing.GroupLayout(main_btn_books);
        main_btn_books.setLayout(main_btn_booksLayout);
        main_btn_booksLayout.setHorizontalGroup(
            main_btn_booksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_btn_booksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(main_label_books, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );
        main_btn_booksLayout.setVerticalGroup(
            main_btn_booksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_btn_booksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(main_label_books, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        main_btn_issues.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                main_btn_issuesMouseClicked(evt);
            }
        });

        main_label_issues.setFont(new java.awt.Font("HelveticaNowDisplay Regular", 0, 14)); // NOI18N
        main_label_issues.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        main_label_issues.setText("Issues");
        main_label_issues.setPreferredSize(new java.awt.Dimension(68, 45));
        main_label_issues.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                main_label_issuesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout main_btn_issuesLayout = new javax.swing.GroupLayout(main_btn_issues);
        main_btn_issues.setLayout(main_btn_issuesLayout);
        main_btn_issuesLayout.setHorizontalGroup(
            main_btn_issuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_btn_issuesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(main_label_issues, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );
        main_btn_issuesLayout.setVerticalGroup(
            main_btn_issuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_btn_issuesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(main_label_issues, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(main_btn_dash, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(main_btn_users, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(main_btn_books, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(main_btn_issues, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(main_btn_dash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(main_btn_users, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(main_btn_books, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(main_btn_issues, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.CardLayout());

        panel_dash.setBackground(new java.awt.Color(102, 255, 255));
        panel_dash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_dashMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_dashLayout = new javax.swing.GroupLayout(panel_dash);
        panel_dash.setLayout(panel_dashLayout);
        panel_dashLayout.setHorizontalGroup(
            panel_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1096, Short.MAX_VALUE)
        );
        panel_dashLayout.setVerticalGroup(
            panel_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        jPanel2.add(panel_dash, "card5");

        panel_users.setBackground(new java.awt.Color(255, 51, 255));

        javax.swing.GroupLayout panel_usersLayout = new javax.swing.GroupLayout(panel_users);
        panel_users.setLayout(panel_usersLayout);
        panel_usersLayout.setHorizontalGroup(
            panel_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1096, Short.MAX_VALUE)
        );
        panel_usersLayout.setVerticalGroup(
            panel_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        jPanel2.add(panel_users, "card4");

        panel_books.setBackground(new java.awt.Color(51, 255, 51));

        javax.swing.GroupLayout panel_booksLayout = new javax.swing.GroupLayout(panel_books);
        panel_books.setLayout(panel_booksLayout);
        panel_booksLayout.setHorizontalGroup(
            panel_booksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1096, Short.MAX_VALUE)
        );
        panel_booksLayout.setVerticalGroup(
            panel_booksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        jPanel2.add(panel_books, "card3");

        panel_issues.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout panel_issuesLayout = new javax.swing.GroupLayout(panel_issues);
        panel_issues.setLayout(panel_issuesLayout);
        panel_issuesLayout.setHorizontalGroup(
            panel_issuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1096, Short.MAX_VALUE)
        );
        panel_issuesLayout.setVerticalGroup(
            panel_issuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        jPanel2.add(panel_issues, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void main_label_dashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_main_label_dashMouseClicked
        // TODO add your handling code here:
        main_btn_dashMouseClicked(evt);
    }//GEN-LAST:event_main_label_dashMouseClicked

    Color lgray = new Color(213,213,213);
    Color dblue = new Color(61,108,185);
    Color tteal = new Color(0,255,240);
    
    private void main_btn_dashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_main_btn_dashMouseClicked
        // TODO add your handling code here:
        panel_dash.setVisible(true);
        panel_users.setVisible(false);
        panel_books.setVisible(false);
        panel_issues.setVisible(false);
        
        main_btn_dash.setBackground(dblue);
        main_btn_users.setBackground(lgray);
        main_btn_books.setBackground(lgray);
        main_btn_issues.setBackground(lgray);
        
        main_label_dash.setForeground(Color.white);
        main_label_users.setForeground(Color.black);
        main_label_books.setForeground(Color.black);
        main_label_issues.setForeground(Color.black);
    }//GEN-LAST:event_main_btn_dashMouseClicked

    private void main_btn_usersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_main_btn_usersMouseClicked
        // TODO add your handling code here:
        panel_dash.setVisible(false);
        panel_users.setVisible(true);
        panel_books.setVisible(false);
        panel_issues.setVisible(false);
        
        main_btn_dash.setBackground(lgray);
        main_btn_users.setBackground(dblue);
        main_btn_books.setBackground(lgray);
        main_btn_issues.setBackground(lgray);
        
        main_label_dash.setForeground(Color.black);
        main_label_users.setForeground(Color.white);
        main_label_books.setForeground(Color.black);
        main_label_issues.setForeground(Color.black);
        
    }//GEN-LAST:event_main_btn_usersMouseClicked

    private void main_btn_booksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_main_btn_booksMouseClicked
        // TODO add your handling code here:
        panel_dash.setVisible(false);
        panel_users.setVisible(false);
        panel_books.setVisible(true);
        panel_issues.setVisible(false);
        
        main_btn_dash.setBackground(lgray);
        main_btn_users.setBackground(lgray);
        main_btn_books.setBackground(dblue);
        main_btn_issues.setBackground(lgray);
        
        main_label_dash.setForeground(Color.black);
        main_label_users.setForeground(Color.black);
        main_label_books.setForeground(Color.white);
        main_label_issues.setForeground(Color.black);
    }//GEN-LAST:event_main_btn_booksMouseClicked

    private void main_btn_issuesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_main_btn_issuesMouseClicked
        // TODO add your handling code here:
        panel_dash.setVisible(false);
        panel_users.setVisible(false);
        panel_books.setVisible(false);
        panel_issues.setVisible(true);
        
        main_btn_dash.setBackground(lgray);
        main_btn_users.setBackground(lgray);
        main_btn_books.setBackground(lgray);
        main_btn_issues.setBackground(dblue);
        
        main_label_dash.setForeground(Color.black);
        main_label_users.setForeground(Color.black);
        main_label_books.setForeground(Color.black);
        main_label_issues.setForeground(Color.white);
    }//GEN-LAST:event_main_btn_issuesMouseClicked

    private void main_label_usersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_main_label_usersMouseClicked
        // TODO add your handling code here:
        main_btn_usersMouseClicked(evt);
    }//GEN-LAST:event_main_label_usersMouseClicked

    private void panel_dashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_dashMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_dashMouseClicked

    private void main_label_booksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_main_label_booksMouseClicked
        // TODO add your handling code here:
        main_btn_booksMouseClicked(evt);
    }//GEN-LAST:event_main_label_booksMouseClicked

    private void main_label_issuesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_main_label_issuesMouseClicked
        // TODO add your handling code here:
        main_btn_issuesMouseClicked(evt);
    }//GEN-LAST:event_main_label_issuesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel main_btn_books;
    private javax.swing.JPanel main_btn_dash;
    private javax.swing.JPanel main_btn_issues;
    private javax.swing.JPanel main_btn_users;
    private javax.swing.JLabel main_label_books;
    private javax.swing.JLabel main_label_dash;
    private javax.swing.JLabel main_label_issues;
    private javax.swing.JLabel main_label_users;
    private javax.swing.JPanel panel_books;
    private javax.swing.JPanel panel_dash;
    private javax.swing.JPanel panel_issues;
    private javax.swing.JPanel panel_users;
    // End of variables declaration//GEN-END:variables
}
